version: "3.3"
services:
  bf2-webadmin:
    container_name: bf2-webadmin
    # image: "nihlen/bf2-webadmin:latest" # Docker Hub
    image: "bf2webadmin-server:latest" # Local build
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
      - "4300:4300"
    volumes:
      - "./bf2/webadmin/Data:/app/Data"
      - "./bf2/webadmin/Logs:/app/Logs"
      - "./bf2/webadmin/ServerLogs:/app/ServerLogs"
      - "./appsecrets.json:/app/Configuration/appsecrets.json"

  bf2-server-1:
    container_name: bf2-server-1
    image: "bf2:bf2hub-pb-mm-webadmin" # Local build
    restart: on-failure
    environment:
      - ENV_SERVER_NAME=Testserver 1
      - ENV_MAX_PLAYERS=16
      - ENV_SERVER_PORT=16567
      - ENV_GAMESPY_PORT=29900
      - ENV_DEMOS_URL=http://www.example.com/
      - ENV_RCON_PASSWORD=rconpw123
      - ENV_BF2WEBADMIN_HOST=bf2-webadmin
      - ENV_BF2WEBADMIN_PORT=4300
      - ENV_BF2WEBADMIN_TIMER_INTERVAL=300
      - ENV_API_KEY=apikey123
    volumes:
      - "./bf2/server-1/server:/home/bf2/srv"
      - "./bf2/server-1/volume:/volume"
    ports:
      - "8000:80/tcp"
      - "4711:4711/tcp"
      - "4712:4712/tcp"
      - "16567:16567/udp"
      - "27901:27901/udp"
      - "29900:29900/udp"

  bf2-server-2:
    container_name: bf2-server-2
    image: "bf2:bf2hub-pb-mm-webadmin" # Local build
    restart: on-failure
    environment:
      - ENV_SERVER_NAME=Testserver 2
      - ENV_MAX_PLAYERS=16
      - ENV_SERVER_PORT=16569
      - ENV_GAMESPY_PORT=29901
      - ENV_DEMOS_URL=http://www.example.com/
      - ENV_RCON_PASSWORD=rconpw123
      - ENV_BF2WEBADMIN_HOST=bf2-webadmin
      - ENV_BF2WEBADMIN_PORT=4300
      - ENV_BF2WEBADMIN_TIMER_INTERVAL=300
      - ENV_API_KEY=apikey123
    volumes:
      - "./bf2/server-2/server:/home/bf2/srv"
      - "./bf2/server-2/volume:/volume"
    ports:
      - "8001:80/tcp"
      - "4721:4711/tcp"
      - "4722:4712/tcp"
      - "16569:16569/udp"
      - "27911:27901/udp"
      - "29901:29901/udp"
